### ISSUE TITLE
Difference to https://github.com/testcontainers/testcontainers-java ?

### ISSUE THREAD

**Issue by arnzel** [ebean-orm/ebean-test-docker#40]
Hi, nice project but does https://github.com/testcontainers/testcontainers-java not the same ?

**Comment by rbygrave** [comment]
Yes and no.

With test containers the docker container lifecycle is somewhat designed around the test code (before, after etc used to explicitly control the lifecycle of the docker containers).  We can do that with this project `ebean-test-docker` and some people not using Ebean do that rather than using test containers (known ports etc). Ebean users generally don't do that though and instead the desire is to keep the docker containers running for the duration of all the tests.  In fact, we typically only stop and remove containers on CI servers, developers would generally keep the containers running so that testing is really fast.  

So this is more orientated to ... `testing like we do with H2 in memory database` but with docker database containers ( + redis, + elasticsearch etc).

The lifecycle of the docker containers was originally oriented to support the maven lifecycle but then that wasn't `transparent` when as developers we want to run a single test via the IDE.  Now, the docker container lifecycle hooks into Ebean's lifecycle (via `ebean-test-config`) meaning as developers we can just run a single test in the IDE and it just works and is fast because typically the container is in fact already running (plus it then works for any command line builds via maven, gradle etc).

On top of the lifecycle difference the database containers are featured to be setup with database(s), user(s), schema, seed sql etc and with `ebean-test-config` the configuration such as url, username, password etc for testing is automatically set as well.

So in these ways when combined with `ebean-test-config` is is reasonably different.

**Comment by arnzel** [comment]
@rbygrave  thanks for explanation

**Comment by rbygrave** [comment]
I'll close this for now.
